import os
import subprocess
import logging
from typing import List

logger = logging.getLogger(__name__)

class PdfCreator:
    """
    Creates a PDF from transcribed text using LaTeX.
    """

    def __init__(self, transcribed_pages: List[List[str]], output_filename: str = "output.pdf"):
        self.transcribed_pages = transcribed_pages
        self.output_filename = output_filename
        self.tex_filename = output_filename.replace(".pdf", ".tex")

    def create_pdf(self):
        """
        Generates the LaTeX source and compiles it to PDF.
        """
        try:
            latex_content = self._generate_latex_content()
            self._write_tex_file(latex_content)
            self._compile_pdf()
            logger.info(f"PDF created successfully: {self.output_filename}")
        except Exception as e:
            logger.error(f"Failed to create PDF: {e}")
            raise

    def _generate_latex_content(self) -> str:
        """
        Constructs the LaTeX document string.
        """
        preamble = r"""\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{parskip}

\geometry{a4paper, margin=1in}

\begin{document}
"""
        body = ""
        for i, page_lines in enumerate(self.transcribed_pages):
            if i > 0:
                body += r"\newpage" + "\n"
            
            # Join lines from the transcriber. 
            # The prompt ensures paragraphs are separated by blank lines.
            page_content = "\n".join(page_lines)
            body += page_content + "\n"

        end_document = r"\end{document}"
        
        return preamble + body + end_document

    def _write_tex_file(self, content: str):
        """
        Writes the LaTeX content to a .tex file.
        """
        with open(self.tex_filename, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"LaTeX source written to: {self.tex_filename}")

    def _compile_pdf(self):
        """
        Runs pdflatex to compile the .tex file.
        """
        logger.info("Compiling PDF with pdflatex...")
        try:
            # Run pdflatex twice to ensure references are correct (though not strictly needed for this simple case)
            # -interaction=nonstopmode prevents hanging on errors
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", self.tex_filename],
                capture_output=True,
                text=True,
                check=True
            )
            logger.debug(result.stdout)
        except subprocess.CalledProcessError as e:
            logger.error("pdflatex compilation failed.")
            logger.error(e.stdout)
            logger.error(e.stderr)
            raise RuntimeError("LaTeX compilation failed. Check logs for details.")
        
        # Cleanup auxiliary files
        self._cleanup()

    def _cleanup(self):
        """
        Removes auxiliary files generated by pdflatex.
        """
        extensions = [".aux", ".log", ".out"]
        base_name = os.path.splitext(self.tex_filename)[0]
        for ext in extensions:
            try:
                os.remove(base_name + ext)
            except OSError:
                pass
